import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React, { PropsWithChildren } from "react";
import { ClientProviders } from "@/app/queryClient";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { getGenres } from "@/server/actions/movieDB";

const schibstedGrotesk = Schibsted_Grotesk({
 subsets: ["latin"],
 weight: ["900", "400"],
 variable: "--schibstedGroteskFont",
});
const lexend = Schibsted_Grotesk({
 subsets: ["latin"],
 variable: "--lexendFont",
});

export const metadata: Metadata = {
 title: "DMovie",
 description: "Generated by create next app",
};

type RootLayoutProps = Readonly<PropsWithChildren>;

export default async function RootLayout({ children }: RootLayoutProps) {
 const genres = await getGenres();
 return (
  <html lang="en">
   <body
    className={cn(
     schibstedGrotesk.variable,
     lexend.variable,
     "overflow-x-hidden font-lexend selection:bg-gray-50 selection:text-gray-900",
    )}
   >
    <ClientProviders>
     <Header genres={genres} />
     {children}
     <Footer />
    </ClientProviders>
   </body>
  </html>
 );
}
