import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import React, { PropsWithChildren } from "react";
import { ClientProviders } from "@/app/queryClient";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import {
 getCountries,
 getGenres,
 getLanguages,
} from "@/server/actions/movieDB";
import ClientContext from "@/components/clientContext";
import { NextUIProvider } from "@nextui-org/react";

const schibstedGrotesk = Schibsted_Grotesk({
 subsets: ["latin"],
 weight: ["900", "400"],
 variable: "--schibstedGroteskFont",
});
const lexend = Schibsted_Grotesk({
 subsets: ["latin"],
 variable: "--lexendFont",
});

export const metadata: Metadata = {
 title: "DMovie",
 description: "Generated by create next app",
};

type RootLayoutProps = Readonly<PropsWithChildren>;

export default async function RootLayout({ children }: RootLayoutProps) {
 const [genres, languages, countries] = await Promise.all([
  getGenres(),
  getLanguages(),
  getCountries(),
 ]);
 return (
  <html lang="en">
   <body
    className={cn(
     schibstedGrotesk.variable,
     lexend.variable,
     "dark overflow-x-hidden font-lexend selection:bg-gray-50 selection:text-gray-900",
    )}
   >
    <NextUIProvider>
     <ClientContext genres={genres} languages={languages} countries={countries}>
      <ClientProviders>
       <Header />
       {children}
       <Footer />
      </ClientProviders>
     </ClientContext>
    </NextUIProvider>
   </body>
  </html>
 );
}
