import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Lenis from "@/app/lenis";
import { PropsWithChildren } from "react";
import { ClientProviders } from "@/app/queryClient";
import { Header } from "@/components/header";

const schibstedGrotesk = Schibsted_Grotesk({
 subsets: ["latin"],
 weight: ["900", "400"],
 variable: "--schibstedGroteskFont",
});
const lexend = Schibsted_Grotesk({
 subsets: ["latin"],
 variable: "--lexendFont",
});

export const metadata: Metadata = {
 title: "DMovie",
 description: "Generated by create next app",
};

type RootLayoutProps = Readonly<PropsWithChildren>;
export default function RootLayout({ children }: RootLayoutProps) {
 return (
  <html lang="en">
   <body
    className={cn(
     schibstedGrotesk.variable,
     lexend.variable,
     "overflow-x-hidden font-lexend",
    )}
   >
    <ClientProviders>
     <Header />
     <Lenis>{children}</Lenis>
    </ClientProviders>
   </body>
  </html>
 );
}
